title: Works by or about William S. Burroughs
email: bradley.p.allen@gmail.com

description: > 
  This site contains catalog information about my collection of works by and about Williams S. Burroughs.

author:
  name: Bradley P. Allen
  email: bradley.p.allen@gmail.com
  twitter: 'bradleypallen'
